<?php
require_once __DIR__ . '/../../app/auth.php';
require_once __DIR__ . '/../components/metrics.php';
if (empty($_SESSION['emailadm'])) { header('Location: '.app_url('adm/login/'), true, 303); exit; }
$db=app_db();
$stats=admin_metrics($db);
$rows=$db->query("SELECT email,externalreference,valor,status,data FROM confirmar_deposito
    ORDER BY STR_TO_DATE(data, '%d/%m/%Y %H:%i') DESC LIMIT 200")->fetch_all(MYSQLI_ASSOC);
$db->close();
$adminActive='depositos'; $adminTitle='Depósitos';
$statusLabel=static function(string $status): string {
    return ['PAID_OUT'=>'Confirmado','WAITING_FOR_APPROVAL'=>'Aguardando','CANCELED'=>'Cancelado','REVIEW'=>'Conferir'][$status] ?? 'Conferir';
};
$statusClass=static function(string $status): string { return $status==='PAID_OUT'?'paid':($status==='CANCELED'?'canceled':'pending'); };
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#101115"><title>Depósitos · Subway Run</title><link rel="stylesheet" href="<?= app_escape(app_url('gerente/manager-premium.css')) ?>?v=2"><link rel="stylesheet" href="<?= app_escape(app_url('adm/admin-shell.css')) ?>?v=<?= filemtime(dirname(__DIR__).'/admin-shell.css') ?>"></head><body class="admin-app">
<?php require dirname(__DIR__).'/components/panel-nav.php'; ?>
<div class="view-heading"><div><small>FINANCEIRO · PIX</small><h1>Depósitos</h1><p>Valores confirmados são contabilizados após a conciliação do pagamento.</p></div><button class="btn outline" type="button" data-admin-refresh>Atualizar</button></div>
<section class="metric-grid" aria-label="Resumo de depósitos"><article class="metric-card green-card"><small>TOTAL CONFIRMADO</small><strong><?= admin_money($stats['deposit_amount']) ?></strong><span>Valor pago pelos clientes</span></article><article class="metric-card"><small>PAGAMENTOS CONFIRMADOS</small><strong><?= number_format($stats['deposits'],0,',','.') ?></strong><span>Registros aprovados</span></article><article class="metric-card warn-card"><small>AGUARDANDO PAGAMENTO</small><strong><?= number_format($stats['pending_deposits'],0,',','.') ?></strong><span>Sem crédito no saldo</span></article><article class="metric-card blue-card"><small>ÚLTIMOS 7 DIAS</small><strong><?= admin_money(array_sum(array_column($stats['deposit_trend'],'amount'))) ?></strong><span>Cobranças geradas e confirmadas</span></article></section>
<section class="surface"><div class="surface-title"><div><small class="overline">ÚLTIMOS 7 DIAS</small><h2>Faturamento via depósitos</h2></div><span class="legend green-dot">Confirmados</span></div><?= admin_trend_html($stats['deposit_trend'],'Depósitos confirmados nos últimos sete dias') ?></section>
<section class="surface"><div class="admin-compact-head"><h2>Histórico de depósitos</h2><div class="admin-tools"><input class="admin-filter" data-admin-filter type="search" placeholder="Buscar e-mail ou referência" aria-label="Buscar depósitos"><select class="admin-filter" data-admin-status aria-label="Filtrar status"><option value="">Todos</option><option value="PAID_OUT">Confirmados</option><option value="WAITING_FOR_APPROVAL">Aguardando</option><option value="CANCELED">Cancelados</option></select></div></div><div class="table-scroll"><table class="admin-table"><thead><tr><th>DATA</th><th>USUÁRIO</th><th>REFERÊNCIA</th><th>VALOR</th><th>STATUS</th></tr></thead><tbody><?php foreach($rows as $row): ?><tr data-admin-row data-status="<?= app_escape((string)$row['status']) ?>"><td><?= app_escape((string)$row['data']) ?></td><td><strong><?= app_escape((string)$row['email']) ?></strong></td><td class="admin-reference"><?= app_escape((string)$row['externalreference']) ?></td><td class="admin-value"><?= admin_money((float)$row['valor']) ?></td><td><span class="admin-status <?= $statusClass((string)$row['status']) ?>"><?= app_escape($statusLabel((string)$row['status'])) ?></span></td></tr><?php endforeach; ?><?php if(!$rows): ?><tr><td colspan="5" class="empty-row">Nenhum depósito registrado.</td></tr><?php endif; ?></tbody></table></div><p class="admin-ggr-note">Mostrando os 200 registros mais recentes. Apenas status confirmado entra nos totais.</p></section>
</div></main><script src="<?= app_escape(app_url('adm/admin-shell.js')) ?>?v=<?= filemtime(dirname(__DIR__).'/admin-shell.js') ?>" defer></script></body></html>
