<?php
require_once __DIR__.'/../app/account.php';
$db=app_db();$user=account_user($db);game_install($db);withdrawal_install($db);
$nomeUnico=$db->query('SELECT nome_unico FROM app LIMIT 1')->fetch_assoc()['nome_unico']??'Subway Run';
$page=max(1,min(10000,(int)($_GET['page']??1)));$offset=($page-1)*20;
$rounds=app_query($db,"SELECT bet,payout,status,created_at FROM game_rounds WHERE email=? ORDER BY created_at DESC LIMIT 21 OFFSET $offset",[$user['email']])->get_result()->fetch_all(MYSQLI_ASSOC);
$withdrawals=app_query($db,"SELECT valor,status,data FROM saques WHERE email=? ORDER BY STR_TO_DATE(data,'%d-%m-%Y %H:%i:%s') DESC LIMIT 21 OFFSET $offset",[$user['email']])->get_result()->fetch_all(MYSQLI_ASSOC);
$deposits=app_query($db,"SELECT valor,status,data FROM confirmar_deposito WHERE email=? ORDER BY STR_TO_DATE(data,'%d/%m/%Y %H:%i') DESC LIMIT 21 OFFSET $offset",[$user['email']])->get_result()->fetch_all(MYSQLI_ASSOC);
$total=app_query($db,'SELECT COUNT(*) n FROM game_rounds WHERE email=?',[$user['email']])->get_result()->fetch_assoc()['n'];
$more=count($rounds)>20||count($withdrawals)>20||count($deposits)>20;
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Meu perfil</title><link rel="stylesheet" href="<?= app_url('arquivos/account.css') ?>"></head><body><?php $menuBase='../';$menuLoggedIn=true;$menuCurrent='perfil/';include __DIR__.'/../components/menu.php'; ?>
<main class="account-shell"><header class="account-heading"><span class="icon-tile"><?= ui_icon('user') ?></span><div><p class="eyebrow">SEU ESPAÇO</p><h1><?= app_escape($user['nome']?:'Meu perfil') ?></h1><p><?= app_escape($user['email']) ?></p></div></header>
<div class="account-grid"><section class="account-card wallet-card"><div class="card-top"><span class="eyebrow">SALDO <?= $user['demo']==='1'?'SIMULADO':'DISPONÍVEL' ?></span><?= ui_icon('wallet') ?></div><strong class="balance"><?= account_money($user['saldo']) ?></strong><a class="account-button" href="<?= app_url('painel/') ?>"><?= ui_icon('play') ?> Jogar agora</a><a class="account-button secondary" href="<?= app_url('afiliate/') ?>"><?= ui_icon('users') ?> Minha rede</a></section><section class="account-card"><h2><?= ui_icon('shield') ?> Dados da conta</h2><div class="activity-row"><div><small>Telefone</small><strong><?= app_escape($user['telefone']) ?></strong></div></div><div class="activity-row"><div><small>Cadastro</small><strong><?= app_escape($user['data_cadastro']) ?></strong></div><span class="chip row-end"><?= $user['demo']==='1'?'Conta demo':'Conta de jogador' ?></span></div></section></div>
<div class="stat-grid"><div class="account-card mini"><?= ui_icon('play') ?><strong><?= (int)$total ?></strong><span>Partidas</span></div><div class="account-card mini"><?= ui_icon('trophy') ?><strong><?= account_money($user['ganhos']) ?></strong><span>Ganhos registrados</span></div><div class="account-card mini"><?= ui_icon('coins') ?><strong><?= account_money($user['depositou']) ?></strong><span>Total depositado</span></div></div>
<?php foreach([['Partidas','play',$rounds],['Depósitos','deposit',$deposits],['Saques','withdraw',$withdrawals]] as [$title,$icon,$rows]): ?><details class="account-card" open><summary><?= ui_icon($icon) ?> Histórico de <?= strtolower($title) ?></summary><?php if(!$rows): ?><div class="empty-state"><?= ui_icon('history') ?><p>Nenhum registro nesta página.</p></div><?php else: foreach(array_slice($rows,0,20) as $item): ?><div class="activity-row"><span class="icon-tile small"><?= ui_icon($icon) ?></span><div><strong><?= app_escape(account_status($item['status'])) ?></strong><small><?= app_escape($item['created_at']??$item['data']) ?></small></div><div class="row-end"><strong><?= account_money($icon==='play'?($item['payout']??0):$item['valor']) ?></strong><?php if($icon==='play'): ?><small>Entrada <?= account_money($item['bet']) ?></small><?php endif; ?></div></div><?php endforeach; endif; ?></details><?php endforeach; ?>
<nav aria-label="Páginas do histórico"><?php if($page>1): ?><a class="account-button secondary" href="?page=<?= $page-1 ?>">Mais recentes</a><?php endif; ?> <span class="chip">Página <?= $page ?></span> <?php if($more): ?><a class="account-button secondary" href="?page=<?= $page+1 ?>">Mais antigos</a><?php endif; ?></nav><a class="account-button danger" href="<?= app_url('logout.php') ?>"><?= ui_icon('logout') ?> Sair da conta</a></main></body></html>
