<?php
require_once __DIR__.'/account.php';
$db=app_db(); $user=account_user($db); withdrawal_install($db);
$nomeUnico=$db->query('SELECT nome_unico FROM app LIMIT 1')->fetch_assoc()['nome_unico']??'Subway Run';
$withdrawals=app_query($db,'SELECT id,valor,status FROM saque_afiliado WHERE email=? ORDER BY id DESC LIMIT 30',[$user['email']])->get_result()->fetch_all(MYSQLI_ASSOC);
$managerPartner=app_query($db,'SELECT p.* FROM manager_partners p WHERE p.influencer_email=? AND p.active=1 LIMIT 1',[$user['email']])->get_result()->fetch_assoc();
$managerCommissionTotal=0.0;
if($managerPartner){
    $invite=app_url('cadastrar/?ref='.rawurlencode($managerPartner['code']).'&by='.rawurlencode((string)$user['id']));
    $refs=app_query($db,'SELECT a.email,a.depositou,a.data_cadastro,a.status_primeiro_deposito FROM manager_referrals r JOIN appconfig a ON a.email COLLATE utf8mb4_unicode_ci=r.email COLLATE utf8mb4_unicode_ci WHERE r.partner_id=? AND r.influencer_email=? ORDER BY r.created_at DESC LIMIT 50',[(string)$managerPartner['id'],$user['email']])->get_result()->fetch_all(MYSQLI_ASSOC);
    $stats=app_query($db,"SELECT COUNT(*) total,COALESCE(SUM(a.status_primeiro_deposito='1'),0) active FROM manager_referrals r JOIN appconfig a ON a.email COLLATE utf8mb4_unicode_ci=r.email COLLATE utf8mb4_unicode_ci WHERE r.partner_id=? AND r.influencer_email=?",[(string)$managerPartner['id'],$user['email']])->get_result()->fetch_assoc();
    $earned=app_query($db,'SELECT COALESCE(SUM(influencer_amount),0) amount FROM manager_commissions WHERE partner_id=? AND influencer_email=?',[(string)$managerPartner['id'],$user['email']])->get_result()->fetch_assoc();
    $managerCommissionTotal=(float)($earned['amount']??0);
}else{
    $invite=app_url('cadastrar/?aff='.rawurlencode($user['id']));
    $refs=app_query($db,'SELECT email,depositou,data_cadastro,status_primeiro_deposito FROM appconfig WHERE afiliado=? ORDER BY data_cadastro DESC LIMIT 50',[$user['id']])->get_result()->fetch_all(MYSQLI_ASSOC);
    $stats=app_query($db,"SELECT COUNT(*) total,COALESCE(SUM(status_primeiro_deposito='1'),0) active FROM appconfig WHERE afiliado=?",[$user['id']])->get_result()->fetch_assoc();
}
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Minha rede · <?= app_escape($nomeUnico) ?></title><link rel="stylesheet" href="<?= app_url('arquivos/account.css') ?>"></head><body>
<?php $menuBase='../';$menuLoggedIn=true;$menuCurrent='afiliate/';include __DIR__.'/../components/menu.php'; ?>
<main class="account-shell"><header class="account-heading"><span class="icon-tile"><?= ui_icon('users') ?></span><div><p class="eyebrow">CONECTE · COMPARTILHE · ACOMPANHE</p><h1>Sua rede, suas conquistas</h1><p>Acompanhe seus convites e a divisão da parceria.</p></div></header>
<div class="account-grid">
<?php if($managerPartner): ?><section class="account-card wallet-card"><div class="card-top"><span class="eyebrow">COMISSÃO REGISTRADA</span><?= ui_icon('wallet') ?></div><strong class="balance"><?= account_money($managerCommissionTotal) ?></strong><p>Parte do influenciador nos depósitos confirmados da sua rede.</p><small>Divisão por depósito: gerente <?= app_escape(number_format((float)$managerPartner['manager_percent'],2,',','.')) ?>% · você <?= app_escape(number_format((float)$managerPartner['influencer_percent'],2,',','.')) ?>% · plataforma 30%.</small></section>
<section class="account-card"><div class="card-top"><h2>Seu link de divulgação</h2><?= ui_icon('link') ?></div><p>Os cadastros feitos pelo seu link serão associados à sua parceria e seguirão esta divisão.</p><input id="invite-link" value="<?= app_escape($invite) ?>" readonly aria-label="Seu link de convite"><button class="account-button secondary" type="button" data-copy-invite><?= ui_icon('copy') ?> Copiar link</button><span id="copy-status" role="status"></span></section>
<?php else: ?><section class="account-card wallet-card"><div class="card-top"><span class="eyebrow">CARTEIRA DE COMISSÕES</span><?= ui_icon('wallet') ?></div><strong class="balance"><?= account_money($user['comissaofake']) ?></strong><p>Você recebe 50% de cada depósito confirmado feito pelo seu link. O valor entra aqui após a confirmação do pagamento.</p><a class="account-button" href="<?= app_url('saque-afiliado/') ?>"><?= ui_icon('withdraw') ?> Sacar comissão <?= ui_icon('arrow') ?></a><small>Solicitações passam por aprovação manual.</small></section><section class="account-card"><div class="card-top"><h2>Seu convite exclusivo</h2><?= ui_icon('link') ?></div><p>Compartilhe seu link e acompanhe sua rede por aqui.</p><input id="invite-link" value="<?= app_escape($invite) ?>" readonly aria-label="Seu link de convite"><button class="account-button secondary" type="button" data-copy-invite><?= ui_icon('copy') ?> Copiar link</button><span id="copy-status" role="status"></span></section><?php endif; ?>
</div><div class="stat-grid"><article class="account-card mini"><?= ui_icon('users') ?><strong><?= (int)$stats['total'] ?></strong><span>Convidados</span></article><article class="account-card mini"><?= ui_icon('check') ?><strong><?= (int)$stats['active'] ?></strong><span>Com depósito confirmado</span></article><?php if(!$managerPartner): ?><article class="account-card mini"><?= ui_icon('coins') ?><strong>50%</strong><span>Comissão por depósito</span></article><?php endif; ?></div>
<section class="account-card"><div class="card-top"><h2><?= ui_icon('users') ?> Sua comunidade</h2><span class="chip">Últimos 50 convites</span></div><?php if(!$refs): ?><div class="empty-state"><?= ui_icon('users') ?><h3>Sua rede começa com um convite.</h3><p>Copie seu link acima. Seus convidados aparecerão aqui.</p></div><?php else: foreach($refs as $ref): ?><div class="activity-row"><span class="icon-tile small"><?= ui_icon('user') ?></span><div><strong><?= app_escape(account_mask($ref['email'])) ?></strong><small><?= app_escape($ref['data_cadastro']) ?></small></div><div class="row-end"><strong><?= account_money($ref['depositou']) ?></strong><small><?= $ref['status_primeiro_deposito']==='1'?'Depósito confirmado':'Aguardando depósito' ?></small></div></div><?php endforeach; endif; ?></section>
<section class="account-card"><h2><?= ui_icon('history') ?> Histórico de saques de comissão</h2><p>Últimas 30 solicitações, incluindo as que estão em análise.</p><?php if(!$withdrawals): ?><div class="empty-state"><?= ui_icon('wallet') ?><p>Você ainda não solicitou saque de comissão.</p></div><?php else: foreach($withdrawals as $item): ?><div class="activity-row"><span class="icon-tile small"><?= ui_icon('withdraw') ?></span><div><strong>Solicitação #<?= (int)$item['id'] ?></strong><small><?= app_escape(account_status($item['status'])) ?></small></div><strong class="row-end"><?= account_money($item['valor']) ?></strong></div><?php endforeach; endif; ?></section></main><script src="<?= app_url('arquivos/account.js') ?>" defer></script></body></html>
