<aside class="sr-sim-toast" id="srSimToast" aria-live="polite" aria-atomic="true" hidden>
    <span class="sr-sim-toast__badge">SIMULAÇÃO</span>
    <span class="sr-sim-toast__mark" aria-hidden="true">↗</span>
    <span class="sr-sim-toast__copy"><strong id="srSimName">Exemplo de atividade</strong><small>Mensagem demonstrativa · não é um saque real</small></span>
    <strong class="sr-sim-toast__amount" id="srSimAmount">R$ 0,00</strong>
</aside>
<style>
.sr-sim-toast{position:fixed;z-index:1200;left:max(14px,env(safe-area-inset-left));bottom:calc(88px + env(safe-area-inset-bottom));width:min(420px,calc(100vw - 28px));display:grid;grid-template-columns:auto 38px minmax(0,1fr) auto;align-items:center;gap:10px;padding:12px 14px;border:1px solid rgba(177,139,255,.34);border-radius:18px;background:linear-gradient(125deg,rgba(19,17,43,.97),rgba(33,21,68,.97));box-shadow:0 14px 38px rgba(0,0,0,.38),0 0 25px rgba(139,92,246,.18);color:#f8f7ff;font:500 13px/1.35 system-ui,sans-serif;animation:srToastIn .38s ease both}.sr-sim-toast[hidden]{display:none}.sr-sim-toast__badge{position:absolute;left:13px;top:-9px;padding:3px 7px;border-radius:99px;background:#ffd34f;color:#241c05;font-size:9px;font-weight:900;letter-spacing:.08em}.sr-sim-toast__mark{grid-column:1;width:36px;height:36px;display:grid;place-items:center;border-radius:50%;background:linear-gradient(140deg,#02dba0,#00a87b);color:#062b27;font-size:21px;font-weight:900}.sr-sim-toast__copy{grid-column:2;grid-row:1;min-width:0;display:flex;flex-direction:column;padding-left:0}.sr-sim-toast__copy strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#fff;font-size:13px}.sr-sim-toast__copy small{color:#c5c1d7;font-size:10px}.sr-sim-toast__amount{grid-column:3;grid-row:1;color:#5cf0c4;font-size:13px;white-space:nowrap}.sr-sim-toast:not([hidden]){grid-template-columns:36px minmax(0,1fr) auto}.sr-sim-toast__mark{grid-column:1}.sr-sim-toast__copy{grid-column:2}.sr-sim-toast__amount{grid-column:3}@keyframes srToastIn{from{opacity:0;transform:translate3d(-12px,10px,0)}to{opacity:1;transform:translate3d(0,0,0)}}@media(max-width:420px){.sr-sim-toast{bottom:calc(78px + env(safe-area-inset-bottom));gap:8px;padding:11px 12px}.sr-sim-toast__copy small{font-size:9px}.sr-sim-toast__amount{font-size:12px}}@media(prefers-reduced-motion:reduce){.sr-sim-toast{animation:none}}
</style>
<script>
(()=>{const box=document.getElementById('srSimToast');if(!box)return;const first=['Ana','Alice','Beatriz','Bruno','Camila','Caio','Clara','Daniel','Eduarda','Felipe','Gabriel','Helena','Igor','Isabela','João','Julia','Lucas','Mariana','Mateus','Rafaela','Thiago','Valentina'];const last=['Almeida','Barbosa','Carvalho','Costa','Dias','Fernandes','Ferreira','Lima','Martins','Mendes','Oliveira','Pereira','Ribeiro','Rocha','Santos','Silva'];const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});function update(){const name=first[Math.floor(Math.random()*first.length)]+' '+last[Math.floor(Math.random()*last.length)][0]+'.';const amount=80+Math.random()*79920;document.getElementById('srSimName').textContent='Exemplo: '+name;document.getElementById('srSimAmount').textContent=money.format(amount);box.hidden=false}window.setTimeout(()=>{update();window.setInterval(update,10500)},2200)})();
</script>
