<?php
require_once __DIR__ . '/../app/manager.php';
$db=app_db(); manager_install($db);
$manager=manager_current($db);
if(!$manager){header('Location: '.app_url('gerente/login.php'));exit;}
$notice='';$error='';$demoCredentials=null;
if(($_SERVER['REQUEST_METHOD']??'')==='POST'){
    try{
        if(!app_check_csrf())throw new InvalidArgumentException('Formulário expirado. Recarregue a página.');
        $action=app_input('action');$managerId=(int)$manager['id'];
        if($action==='partner'){
            if(!is_numeric(app_input('manager_percent'))||!is_numeric(app_input('influencer_percent')))throw new InvalidArgumentException('Informe os dois percentuais.');
            manager_partner_create($db,$managerId,app_input('name'),(float)app_input('manager_percent'),(float)app_input('influencer_percent'));
            $notice='Link exclusivo criado com sucesso.';
        }elseif($action==='update'){
            $id=(int)app_input('id');$mp=(float)app_input('manager_percent');$ip=(float)app_input('influencer_percent');
            if($id<1||!is_numeric(app_input('manager_percent'))||!is_numeric(app_input('influencer_percent'))||$mp<0||$ip<0||abs($mp+$ip-MANAGER_BUDGET_PERCENT)>.0001)throw new InvalidArgumentException('Divida exatamente 70% entre gerente e influenciador.');
            if(!app_query($db,'SELECT id FROM manager_partners WHERE id=? AND manager_id=?',[(string)$id,(string)$managerId])->get_result()->fetch_assoc())throw new InvalidArgumentException('Convite não encontrado.');
            app_query($db,'UPDATE manager_partners SET manager_percent=?,influencer_percent=? WHERE id=? AND manager_id=?',[(string)$mp,(string)$ip,(string)$id,(string)$managerId]);
            $notice='Divisão atualizada para os próximos depósitos.';
        }elseif($action==='toggle'){
            $id=(int)app_input('id');if($id<1)throw new InvalidArgumentException('Convite inválido.');
            $stmt=app_query($db,'UPDATE manager_partners SET active=1-active WHERE id=? AND manager_id=?',[(string)$id,(string)$managerId]);
            if($stmt->affected_rows!==1)throw new InvalidArgumentException('Convite não encontrado.');
            $notice='Status do convite atualizado.';
        }elseif($action==='demo_auto'){
            $demoCredentials=manager_demo_create_auto($db,$managerId);
            $notice='Conta demo criada automaticamente. Copie os dados de acesso agora.';
        }elseif($action==='demo_update'){
            manager_demo_update($db,$managerId,app_input('email'),app_input('name'),app_input('balance'),app_input('password'));
            $notice='Conta demo atualizada com sucesso.';
        }elseif($action==='demo_balance'){
            manager_demo_set_balance($db,$managerId,app_input('email'),app_input('balance'));
            $notice='Saldo da conta demo atualizado.';
        }elseif($action==='payout'){
            $nonce=app_input('nonce');
            if($nonce===''||empty($_SESSION['manager_payout_nonce'])||!hash_equals($_SESSION['manager_payout_nonce'],$nonce))throw new InvalidArgumentException('Esta solicitação já foi enviada. Atualize a página.');
            unset($_SESSION['manager_payout_nonce']);manager_payout_request($db,$managerId,app_input('amount'),app_input('pix_key'));
            $notice='Saque solicitado. Acompanhe o status nesta página.';
        }else throw new InvalidArgumentException('Ação inválida.');
    }catch(mysqli_sql_exception $e){error_log('manager panel: '.$e->getMessage());$error=$e->getCode()===1062?'Este cadastro já existe.':'Não foi possível salvar. Tente novamente.';}
    catch(InvalidArgumentException $e){$error=$e->getMessage();}
    catch(Throwable $e){error_log('manager panel: '.$e->getMessage());$error='Não foi possível concluir a operação.';}
}
$managerId=(string)$manager['id'];
$partners=app_query($db,'SELECT p.*,(SELECT COUNT(*) FROM manager_referrals r WHERE r.partner_id=p.id) AS leads FROM manager_partners p WHERE p.manager_id=? ORDER BY p.id DESC',[$managerId])->get_result()->fetch_all(MYSQLI_ASSOC);
$demos=app_query($db,"SELECT d.email,d.display_name,d.created_at,a.saldo FROM manager_demos d JOIN appconfig a ON a.email COLLATE utf8mb4_unicode_ci=d.email COLLATE utf8mb4_unicode_ci AND a.demo=1 WHERE d.manager_id=? ORDER BY d.created_at DESC LIMIT 100",[$managerId])->get_result()->fetch_all(MYSQLI_ASSOC);
$totals=app_query($db,'SELECT COUNT(*) deposits,COALESCE(SUM(deposit_amount),0) volume,COALESCE(SUM(manager_amount),0) manager_total FROM manager_commissions WHERE manager_id=?',[$managerId])->get_result()->fetch_assoc();
$recent=app_query($db,'SELECT c.*,p.name FROM manager_commissions c JOIN manager_partners p ON p.id=c.partner_id WHERE c.manager_id=? ORDER BY c.created_at DESC LIMIT 20',[$managerId])->get_result()->fetch_all(MYSQLI_ASSOC);
$available=manager_payout_available($db,(int)$manager['id']);
$payouts=app_query($db,'SELECT id,amount,status,created_at FROM manager_payout_requests WHERE manager_id=? ORDER BY id DESC LIMIT 20',[$managerId])->get_result()->fetch_all(MYSQLI_ASSOC);
$host=(string)($_SERVER['HTTP_HOST']??'localhost');if(!preg_match('/^[a-zA-Z0-9.:-]+$/D',$host))$host='localhost';
$origin=(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off'?'https':'http').'://'.$host;
$money=static fn($value):string=>'R$ '.number_format((float)$value,2,',','.');
$statusLabel=static fn($status):string=>['PENDING'=>'Em análise','PAID'=>'Pago','REJECTED'=>'Recusado'][$status]??$status;
$_SESSION['manager_payout_nonce']=bin2hex(random_bytes(24));
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Painel do gerente • Subway Run</title><link rel="stylesheet" href="<?=app_escape(app_url('gerente/manager.css'))?>?v=5"><link rel="stylesheet" href="<?=app_escape(app_url('gerente/mobile.css'))?>?v=3"></head><body><main class="shell">
<header class="head"><div><div class="logo">SUBWAY <span>RUN</span></div><span class="kicker">PAINEL DO GERENTE</span><h1>Olá, <?=app_escape($manager['name'])?></h1><p>Gerencie suas parcerias, comissões e acessos de demonstração.</p></div><a class="link-pill" href="<?=app_escape(app_url('gerente/logout.php'))?>"><?=ui_icon('logout')?> Sair</a></header>
<?php if($notice):?><div class="notice success" role="status"><?=app_escape($notice)?></div><?php endif;?><?php if($error):?><div class="notice error" role="alert"><?=app_escape($error)?></div><?php endif;?>
<?php if($demoCredentials):?><section class="credential-card"><div><span class="kicker">ACESSO CRIADO</span><h2><?=ui_icon('check')?> Conta demo pronta</h2><p>Copie estes dados antes de sair desta página.</p></div><div class="credential-grid"><label>Nome<input readonly value="<?=app_escape($demoCredentials['name'])?>"></label><label>E-mail<input readonly value="<?=app_escape($demoCredentials['email'])?>"></label><label>Senha<input readonly value="<?=app_escape($demoCredentials['password'])?>"></label></div><button class="copy-all" type="button" data-copy-credentials="<?=app_escape($demoCredentials['email']."\n".$demoCredentials['password'])?>"><?=ui_icon('copy')?> Copiar acesso</button></section><?php endif;?>
<section class="stats"><div class="stat"><span>COMISSÃO DISPONÍVEL</span><strong><?=$money($available)?></strong><small>Disponível para saque</small></div><div class="stat"><span>PARTE CALCULADA</span><strong><?=$money($totals['manager_total'])?></strong><small><?=(int)$totals['deposits']?> depósitos</small></div><div class="stat"><span>LEADS CADASTRADOS</span><strong><?=array_sum(array_map(static fn($p)=>(int)$p['leads'],$partners))?></strong><small>Por seus links</small></div><div class="stat"><span>CONTAS DEMO</span><strong><?=count($demos)?></strong><small>Acessos sob gestão</small></div></section>
<div class="grid"><section class="panel"><span class="kicker">CARTEIRA</span><h2><?=ui_icon('wallet')?> Sacar comissão</h2><p class="muted">Solicite a retirada do saldo disponível para sua chave PIX.</p><form method="post"><input type="hidden" name="csrf" value="<?=app_escape(app_csrf())?>"><input type="hidden" name="nonce" value="<?=app_escape($_SESSION['manager_payout_nonce'])?>"><input type="hidden" name="action" value="payout"><label>Valor (R$)<input name="amount" type="number" min="1" max="<?=app_escape($available)?>" step="0.01" required></label><label>Chave PIX<input name="pix_key" maxlength="77" required></label><button class="primary" <?= (float)$available<1?'disabled':''?>><?=ui_icon('withdraw')?> Solicitar saque</button></form></section>
<section class="panel demo-create"><span class="kicker">DEMONSTRAÇÃO</span><h2><?=ui_icon('user')?> Novo acesso demo</h2><p class="muted">O sistema gera automaticamente nome, e-mail, senha e saldo inicial. Depois você pode editar a conta.</p><form method="post"><input type="hidden" name="csrf" value="<?=app_escape(app_csrf())?>"><input type="hidden" name="action" value="demo_auto"><div class="automatic-list"><span><?=ui_icon('check')?> Credenciais exclusivas</span><span><?=ui_icon('check')?> Modo fácil liberado</span><span><?=ui_icon('check')?> Saldo de treino editável</span></div><button class="primary" type="submit"><?=ui_icon('spark')?> Criar conta automaticamente</button></form></section></div>
<section class="panel wide"><div class="section-head"><div><span class="kicker">CONTAS DEMO</span><h2><?=ui_icon('users')?> Usuários de demonstração</h2><p class="muted">Edite nome, saldo e senha de cada acesso criado por você.</p></div><span class="count-badge"><?=count($demos)?> contas</span></div><?php if(!$demos):?><div class="empty-state"><?=ui_icon('user')?><strong>Nenhuma conta criada</strong><span>Use o botão acima para gerar o primeiro acesso.</span></div><?php else:?><div class="demo-grid"><?php foreach($demos as $demo):?><article class="demo-card"><div class="demo-avatar"><?=strtoupper(app_escape(substr($demo['display_name']?:'D',0,1)))?><span></span></div><div class="demo-info"><strong><?=app_escape($demo['display_name']?:'Conta demo')?></strong><small><?=app_escape($demo['email'])?></small><b><?=$money($demo['saldo'])?></b></div><button type="button" class="mini edit-demo" data-email="<?=app_escape($demo['email'])?>" data-name="<?=app_escape($demo['display_name']?:'Conta demo')?>" data-balance="<?=app_escape($demo['saldo'])?>"><?=ui_icon('edit')?> Editar conta</button></article><?php endforeach;?></div><?php endif;?></section>
<div class="grid"><section class="panel"><span class="kicker">PARCERIAS</span><h2><?=ui_icon('link')?> Criar link de influenciador</h2><p class="muted">Distribua os 70% entre você e o influenciador.</p><form method="post"><input type="hidden" name="csrf" value="<?=app_escape(app_csrf())?>"><input type="hidden" name="action" value="partner"><label>Nome do influenciador<input name="name" maxlength="120" required></label><div class="fields"><label>Gerente (%)<input name="manager_percent" type="number" min="0" max="70" step="0.01" value="35" required></label><label>Influenciador (%)<input name="influencer_percent" type="number" min="0" max="70" step="0.01" value="35" required></label></div><div class="budget"><span>Restante dos 70%</span><strong id="budget-left">0%</strong></div><button class="primary"><?=ui_icon('link')?> Criar link exclusivo</button></form></section>
<section class="panel"><span class="kicker">SAQUES</span><h2><?=ui_icon('history')?> Solicitações recentes</h2><?php if(!$payouts):?><div class="empty-state compact"><span>Nenhuma solicitação enviada.</span></div><?php else:?><div class="rows"><?php foreach($payouts as $payout):?><div class="row"><div><strong>#<?=(int)$payout['id']?> • <?=$money($payout['amount'])?></strong><small><?=app_escape($payout['created_at'])?></small></div><span class="status status-<?=strtolower(app_escape($payout['status']))?>"><?=app_escape($statusLabel($payout['status']))?></span></div><?php endforeach;?></div><?php endif;?></section></div>
<section class="panel wide"><span class="kicker">LINKS ATIVOS</span><h2><?=ui_icon('link')?> Influenciadores e divisões</h2><?php if(!$partners):?><div class="empty-state compact"><span>Crie seu primeiro link para acompanhar os cadastros.</span></div><?php endif;?><div class="partner-list"><?php foreach($partners as $partner):$link=$origin.app_url('cadastrar/?ref='.$partner['code']);?><article class="partner"><div class="partner-head"><div><h3><?=app_escape($partner['name'])?></h3><span class="muted"><?=(int)$partner['leads']?> cadastros • <?=$partner['active']?'Ativo':'Pausado'?></span></div><span class="status <?=$partner['active']?'status-active':'status-paused'?>"><?=$partner['active']?'Ativo':'Pausado'?></span></div><div class="copy-line"><input value="<?=app_escape($link)?>" readonly><button type="button" class="copy" data-copy="<?=app_escape($link)?>"><?=ui_icon('copy')?> Copiar</button></div><div class="partner-controls"><form method="post" class="split-form"><input type="hidden" name="csrf" value="<?=app_escape(app_csrf())?>"><input type="hidden" name="action" value="update"><input type="hidden" name="id" value="<?=(int)$partner['id']?>"><label>Gerente %<input type="number" name="manager_percent" min="0" max="70" step="0.01" value="<?=app_escape($partner['manager_percent'])?>"></label><label>Influenciador %<input type="number" name="influencer_percent" min="0" max="70" step="0.01" value="<?=app_escape($partner['influencer_percent'])?>"></label><button class="mini">Salvar divisão</button></form><form method="post"><input type="hidden" name="csrf" value="<?=app_escape(app_csrf())?>"><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?=(int)$partner['id']?>"><button class="mini <?=$partner['active']?'off':'on'?>"><?=$partner['active']?'Pausar':'Ativar'?></button></form></div></article><?php endforeach;?></div></section>
<section class="panel wide"><span class="kicker">MOVIMENTAÇÃO</span><h2><?=ui_icon('history')?> Comissões calculadas</h2><?php if(!$recent):?><div class="empty-state compact"><span>Nenhum depósito atribuído ainda.</span></div><?php else:?><div class="table-wrap"><table><thead><tr><th>Influenciador</th><th>Depósito</th><th>Gerente</th><th>Influenciador</th><th>Data</th></tr></thead><tbody><?php foreach($recent as $entry):?><tr><td><?=app_escape($entry['name'])?></td><td><?=$money($entry['deposit_amount'])?></td><td><?=$money($entry['manager_amount'])?></td><td><?=$money($entry['influencer_amount'])?></td><td><?=app_escape($entry['created_at'])?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<dialog id="demoEditor" class="manager-dialog"><form method="post"><input type="hidden" name="csrf" value="<?=app_escape(app_csrf())?>"><input type="hidden" name="action" value="demo_update"><input type="hidden" name="email" id="demoEmail"><div class="dialog-head"><div><span class="kicker">EDITAR CONTA</span><h2>Configurar usuário demo</h2></div><button type="button" class="dialog-close" data-close-dialog aria-label="Fechar">×</button></div><p class="dialog-email" id="demoEmailLabel"></p><label>Nome de exibição<input name="name" id="demoName" maxlength="120" required></label><label>Saldo de treino (R$)<input name="balance" id="demoBalance" type="number" min="0" max="999999.99" step="0.01" required></label><label>Nova senha <small>deixe vazio para manter a atual</small><input name="password" type="password" minlength="8" maxlength="72" autocomplete="new-password"></label><button class="primary" type="submit"><?=ui_icon('check')?> Salvar alterações</button></form></dialog>
<p class="footer">Subway Run • Painel do gerente</p></main><script src="<?=app_escape(app_url('gerente/manager.js'))?>?v=4" defer></script></body></html>
