<?php
require_once __DIR__.'/../app/manager.php';
header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store, private');
try{
    $db=app_db();manager_install($db);$manager=manager_current($db);
    if(!$manager){http_response_code(401);echo json_encode(['error'=>'Sessão expirada.']);exit;}
    $email=trim((string)($_GET['email']??''));if(!filter_var($email,FILTER_VALIDATE_EMAIL)){http_response_code(400);echo json_encode(['error'=>'Indicado inválido.']);exit;}
    $owner=app_query($db,'SELECT a.id,a.nome,a.email,a.telefone,a.data_cadastro,a.saldo,a.depositou,a.comissaofake,a.status_primeiro_deposito,p.id partner_id,p.name partner_name,p.influencer_email root_email,r.influencer_email FROM manager_referrals r JOIN manager_partners p ON p.id=r.partner_id JOIN appconfig a ON a.email=r.email WHERE p.manager_id=? AND r.email=? LIMIT 1',[(string)$manager['id'],$email])->get_result()->fetch_assoc();
    if(!$owner){http_response_code(404);echo json_encode(['error'=>'Este indicado não pertence à sua rede.']);exit;}
    $depStats=['total'=>(float)($owner['depositou']??0),'count'=>0,'max'=>0.0,'avg'=>0.0,'rows'=>[]];
    try{$depAgg=app_query($db,"SELECT COUNT(*) count,COALESCE(MAX(CAST(valor AS DECIMAL(12,2))),0) max_value,COALESCE(AVG(CAST(valor AS DECIMAL(12,2))),0) avg_value FROM confirmar_deposito WHERE email=? AND UPPER(status) IN ('PAID_OUT','PAID','APPROVED','APROVADO','PAGO') AND CAST(valor AS DECIMAL(12,2))>0",[$email])->get_result()->fetch_assoc()?:[];$depStats['count']=(int)($depAgg['count']??0);$depStats['max']=(float)($depAgg['max_value']??0);$depStats['avg']=(float)($depAgg['avg_value']??0);$depRows=app_query($db,"SELECT valor,data FROM confirmar_deposito WHERE email=? AND UPPER(status) IN ('PAID_OUT','PAID','APPROVED','APROVADO','PAGO') AND CAST(valor AS DECIMAL(12,2))>0 ORDER BY STR_TO_DATE(data,'%d/%m/%y, %H:%i') DESC, STR_TO_DATE(data,'%d/%m/%Y %H:%i:%s') DESC LIMIT 8",[$email])->get_result()->fetch_all(MYSQLI_ASSOC);$depStats['rows']=$depRows;}catch(Throwable $ignored){}
    $comms=app_query($db,'SELECT COALESCE(SUM(manager_amount),0) amount,COUNT(*) operations FROM manager_commissions WHERE manager_id=? AND referred_email=?',[(string)$manager['id'],$email])->get_result()->fetch_assoc()?:[];
    $commRows=app_query($db,'SELECT deposit_amount,manager_amount,created_at FROM manager_commissions WHERE manager_id=? AND referred_email=? ORDER BY created_at DESC LIMIT 8',[(string)$manager['id'],$email])->get_result()->fetch_all(MYSQLI_ASSOC);
    $withdraw=['approved'=>0.0,'pending'=>0.0];
    try{if($db->query("SHOW TABLES LIKE 'saques'")->num_rows){$row=app_query($db,"SELECT COALESCE(SUM(CASE WHEN LOWER(status) IN ('pago','paid','paid_out','concluído','concluido','aprovado','approved') THEN CAST(valor AS DECIMAL(12,2)) ELSE 0 END),0) approved,COALESCE(SUM(CASE WHEN LOWER(status) IN ('pending','pendente','em análise','em analise','processing') THEN CAST(valor AS DECIMAL(12,2)) ELSE 0 END),0) pending FROM saques WHERE email=?",[$email])->get_result()->fetch_assoc();if($row)$withdraw=['approved'=>(float)$row['approved'],'pending'=>(float)$row['pending']];}}catch(Throwable $ignored){}
    $games=['total'=>0,'wins'=>0,'losses'=>0];
    try{if($db->query("SHOW TABLES LIKE 'game_rounds'")->num_rows){$row=app_query($db,"SELECT COUNT(*) total,COALESCE(SUM(status='WIN'),0) wins,COALESCE(SUM(status='LOSS'),0) losses FROM game_rounds WHERE email=?",[$email])->get_result()->fetch_assoc();if($row)$games=array_map('intval',$row);}}catch(Throwable $ignored){}
    $children=app_query($db,'SELECT id,nome,telefone,depositou FROM appconfig WHERE afiliado=? ORDER BY data_cadastro DESC LIMIT 200',[(string)$owner['id']])->get_result()->fetch_all(MYSQLI_ASSOC);
    $networkDeposit=0.0;foreach($children as $child)$networkDeposit+=(float)($child['depositou']??0);
    $level=manager_referral_level($db,(int)$owner['partner_id'],(string)$owner['root_email'],(string)$owner['influencer_email']);
    $data=['name'=>$owner['nome']?:'Usuário','email'=>$owner['email'],'phone'=>$owner['telefone'],'registered'=>$owner['data_cadastro'],'partner'=>$owner['partner_name'],'level'=>'N'.$level,'balance'=>(float)$owner['saldo'],'affiliate_balance'=>(float)$owner['comissaofake'],'deposits'=>$depStats,'commission'=>['total'=>(float)($comms['amount']??0),'count'=>(int)($comms['operations']??0),'rows'=>$commRows],'withdrawals'=>$withdraw,'games'=>$games,'network'=>['count'=>count($children),'deposits'=>$networkDeposit,'commission'=>(float)$owner['comissaofake'],'members'=>$children]];
    echo json_encode($data,JSON_UNESCAPED_UNICODE|JSON_INVALID_UTF8_SUBSTITUTE|JSON_PARTIAL_OUTPUT_ON_ERROR);
}catch(Throwable $e){error_log('manager referral detail: '.$e->getMessage());http_response_code(503);echo json_encode(['error'=>'Não foi possível carregar os detalhes agora.']);}
