<?php
require_once __DIR__.'/../../app/manager.php';
$db=app_db();
manager_install($db);
$demoPasswords=[];
foreach($db->query('SELECT email,password_encrypted FROM manager_demos')->fetch_all(MYSQLI_ASSOC) as $demoRow){
    try{$demoPasswords[strtolower((string)$demoRow['email'])]=manager_demo_decrypt_password((string)($demoRow['password_encrypted']??''));}
    catch(Throwable $e){error_log('admin demo password view: '.$e->getMessage());}
}
$users=$db->query("SELECT id,nome,email,telefone,saldo,depositou,indicados,plano,cpa,comissaofake,afiliado_ativo,bloc,demo,data_cadastro,total_apostado FROM appconfig ORDER BY CAST(id AS UNSIGNED) DESC LIMIT 1000")->fetch_all(MYSQLI_ASSOC);
foreach($users as &$user)$user['demo_password']=$user['demo']==='1'?($demoPasswords[strtolower((string)$user['email'])]??''):'';unset($user);
$summary=$db->query("SELECT COUNT(*) total,SUM(CASE WHEN demo='1' THEN 1 ELSE 0 END) demos,COALESCE(SUM(CAST(saldo AS DECIMAL(14,2))),0) balance,COALESCE(SUM(CAST(depositou AS DECIMAL(14,2))),0) deposits FROM appconfig")->fetch_assoc();
$notice=$_SESSION['admin_notice']??'';unset($_SESSION['admin_notice']);
$money=static fn($value):string=>'R$ '.number_format((float)($value?:0),2,',','.');
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Usuários • Administração Subway Run</title><link rel="stylesheet" href="<?=app_escape(app_url('adm/usuarios/users.css'))?>?v=3"></head><body class="sk-admin"><main class="usr-shell">
<header class="usr-head"><div><a class="usr-brand" href="<?=app_escape(app_url('adm/'))?>">SUBWAY <span>RUN</span></a><p>ADMINISTRAÇÃO</p><h1>Gestão de usuários</h1><span>Visualize contas, saldos e acessos em um painel organizado.</span></div><div class="usr-head-actions"><a href="<?=app_escape(app_url('adm/'))?>">← Painel principal</a><a href="<?=app_escape(app_url('adm/conta/'))?>">Minha conta</a><a class="usr-exit" href="<?=app_escape(app_url('adm/logout.php'))?>"><?=ui_icon('logout')?> Sair</a></div></header>
<?php if($notice):?><div class="usr-notice" role="status"><?=app_escape($notice)?></div><?php endif;?>
<section class="usr-stats"><article><span>USUÁRIOS</span><strong><?=number_format((int)$summary['total'],0,',','.')?></strong><small>Contas cadastradas</small></article><article><span>CONTAS DEMO</span><strong><?=number_format((int)$summary['demos'],0,',','.')?></strong><small>Acessos de treinamento</small></article><article><span>SALDO TOTAL</span><strong><?=$money($summary['balance'])?></strong><small>Saldo disponível nas contas</small></article><article><span>DEPÓSITOS</span><strong><?=$money($summary['deposits'])?></strong><small>Volume registrado</small></article></section>
<section class="usr-panel"><div class="usr-panel-head"><div><p>CONTAS CADASTRADAS</p><h2><?=ui_icon('users')?> Usuários da plataforma</h2></div><div class="usr-search"><?=ui_icon('search')?><input id="userSearch" type="search" placeholder="Buscar por nome, e-mail ou telefone" autocomplete="off"></div></div>
<div class="usr-filter-bar"><div class="usr-filters" role="group" aria-label="Filtrar usuários"><button type="button" class="active" data-filter="all" aria-pressed="true">Todos</button><button type="button" data-filter="real" aria-pressed="false">Usuários</button><button type="button" data-filter="demo" aria-pressed="false">Demo</button><button type="button" data-filter="blocked" aria-pressed="false">Bloqueados</button></div><span id="filterCount" aria-live="polite"></span></div>
<?php if(!$users):?><div class="usr-empty">Nenhum usuário cadastrado.</div><?php else:?><div class="usr-table-wrap"><table><thead><tr><th>Usuário</th><th>Tipo</th><th>Saldo</th><th>Depositado</th><th>Cadastro</th><th>Status</th><th>Ações</th></tr></thead><tbody id="userRows"><?php foreach($users as $user):$blocked=in_array(strtolower((string)$user['bloc']),['1','true','on'],true);$name=trim((string)$user['nome'])?:explode('@',(string)$user['email'])[0];?><tr data-search="<?=app_escape(strtolower($name.' '.$user['email'].' '.$user['telefone']))?>" data-kind="<?=$user['demo']==='1'?'demo':'real'?>" data-blocked="<?=$blocked?'1':'0'?>"><td><div class="usr-person"><span><?=strtoupper(app_escape(substr($name,0,1)))?></span><div><strong><?=app_escape($name)?></strong><small><?=app_escape($user['telefone']?:'Telefone não informado')?></small></div></div></td><td><span class="usr-badge <?=$user['demo']==='1'?'demo':'real'?>"><?=$user['demo']==='1'?'Demo':'Usuário'?></span></td><td><b class="usr-money"><?=$money($user['saldo'])?></b></td><td><?=$money($user['depositou'])?></td><td><?=app_escape($user['data_cadastro']?:'Não informado')?></td><td><span class="usr-status <?=$blocked?'blocked':'active'?>"><i></i><?=$blocked?'Bloqueado':'Ativo'?></span></td><td><button class="usr-edit" type="button" data-user='<?=app_escape(json_encode($user,JSON_UNESCAPED_UNICODE|JSON_HEX_APOS|JSON_HEX_QUOT))?>'><?=ui_icon('edit')?> Visualizar e editar</button></td></tr><?php endforeach;?></tbody></table></div><div class="usr-empty" id="noResults" hidden>Nenhuma conta encontrada com este filtro.</div><?php endif;?></section>
<dialog class="usr-dialog" id="userDialog"><form action="<?=app_escape(app_url('adm/usuarios/update.php'))?>" method="post"><input type="hidden" name="csrf" value="<?=app_escape(app_csrf())?>"><input type="hidden" name="id" id="editId"><div class="usr-dialog-head"><div><p>DETALHES DA CONTA</p><h2>Editar usuário</h2></div><button type="button" data-close aria-label="Fechar">×</button></div><div class="usr-account-summary"><span id="editAvatar">U</span><div><strong id="editSummaryName">Usuário</strong><small id="editSummaryType">Conta da plataforma</small></div></div><div class="usr-form-grid"><label>Nome<input name="nome" id="editName" maxlength="120" required></label><label>E-mail<input name="email" id="editEmail" type="email" maxlength="254" required></label><label>Telefone<input name="telefone" id="editPhone" inputmode="numeric" maxlength="13"></label><label>Saldo da conta (R$)<input name="saldo" id="editBalance" type="text" inputmode="decimal" autocomplete="off" placeholder="0,00" required><small>Use vírgula ou ponto nos centavos.</small></label><label>Saldo de comissão (R$)<input name="comissaofake" id="editCommission" type="number" min="0" max="9999999999" step="0.01" required></label><label>Comissão sobre depósito<input id="editPlanDisplay" type="text" value="50%" readonly><input name="plano" id="editPlan" type="hidden" value="50"></label><label>Nova senha <small>deixe vazio para manter</small><input name="senha" type="password" minlength="6" maxlength="72" autocomplete="new-password"></label><label id="demoPasswordLabel" hidden>Senha da conta demo<input id="editDemoPassword" type="text" readonly autocomplete="off"><small>Contas demo antigas sem senha recuperável podem receber uma nova senha acima.</small></label></div><div class="usr-switches"><label><input type="checkbox" name="bloqueado" id="editBlocked"><span>Bloquear acesso</span></label></div><div class="usr-readonly"><div><span>Total depositado</span><strong id="viewDeposited">R$ 0,00</strong></div><div><span>Total apostado</span><strong id="viewWagered">R$ 0,00</strong></div><div><span>Indicados</span><strong id="viewReferrals">0</strong></div></div><button class="usr-save" type="submit"><?=ui_icon('check')?> Salvar alterações</button><div class="usr-delete-zone"><strong>Excluir usuário</strong><p>Contas com movimentação financeira ou vínculos ativos não podem ser apagadas. Informe sua senha de administrador para confirmar.</p><label>Senha do administrador<input name="admin_password" type="password" autocomplete="current-password"></label><button class="usr-edit usr-danger" type="submit" formnovalidate formaction="<?=app_escape(app_url('adm/usuarios/delete.php'))?>" onclick="return confirm('Excluir permanentemente esta conta sem movimentação?')">Excluir esta conta</button></div></form></dialog>
</main><script src="<?=app_escape(app_url('adm/usuarios/users.js'))?>?v=3" defer></script></body></html>
